### PR TITLE
Install Frontend Stack

### LINKED ISSUE #24: FrontEnd: Set Up
Set Up Angular 4 and Bootstrap 4 for work on the frontends.

### PR DESCRIPTION
**Pull request by say25**
Install tech stack needed for frontend development.

Highlights Includes:
1. Angular (4.3.6)
2. @ng-bootstrap
3. Bootstrap (4.0.0-beta)
4. TSLinter
5. FontAwesome

This closes #24

### CODE REVIEW

**Review by kassemsandarusi — CHANGES_REQUESTED** [review]
Place .gitignore from skeleton at the root of the repo. The .gitignore has files listed that you currently have added in this changeset. Should they be excluded?

**Comment by say25** [comment]
@kassemsandarusi I can definitely merge the new .gitignore and update the contained ignored files to reflect the move. 

I’m just not sure what files I included that you think are ignored by the current .gitignore?

**Comment by kassemsandarusi** [comment]
new .gitignore created by the skeleton has .vscode files ignored that you currently have included.

**Comment by kassemsandarusi** [comment]
Example .vscode/launch.json, .vscode/tasks.json, etc.

**Comment by say25** [comment]
`.vscode/*` is not ignored as it sits at the root directory while the ignored `.vscode/*` reference in the new `.gitignore` is relative to `Game/Game` so it’s ignoring on that sits there

**Comment by kassemsandarusi** [comment]
Not entirely sure what you mean. We should likely ignore all .vscode directories, you should be able to move the new .gitignore to the root and remove the added .vscode files that are in your changeset.

**Review by kassemsandarusi — APPROVED** [review]

**Pull request merged**
